# Generated by Django 4.2.15 on 2024-08-25 20:53

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_education_details_resume_educations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigIntegerField(default=1724619182690, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.BigIntegerField(default=1724619182691, editable=False, primary_key=True, serialize=False),
        ),
    ]
