# Generated by Django 4.2.15 on 2024-08-25 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_resume_file_alter_resume_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigIntegerField(default=1724620185092, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.BigIntegerField(default=1724620185093, editable=False, primary_key=True, serialize=False),
        ),
    ]
