# Generated by Django 4.2.15 on 2024-08-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resume_id_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.BigIntegerField(default=1724708196893, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='id',
            field=models.BigIntegerField(default=1724708196894, editable=False, primary_key=True, serialize=False),
        ),
    ]
