# Generated by Django 4.2.15 on 2024-08-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_uploadedfile_is_error_alter_resume_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.BigIntegerField(
                default=1724742278094, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.BigIntegerField(
                default=1724742278095, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
