# Generated by Django 4.2.15 on 2024-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_resume_id_alter_uploadedfile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.BigIntegerField(
                default=1724742544946, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.BigIntegerField(
                default=1724742544947, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
