# Generated by Django 4.2.15 on 2024-08-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_uploadedfile_error_alter_resume_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="json",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="id",
            field=models.BigIntegerField(
                default=1724749665149, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="id",
            field=models.BigIntegerField(
                default=1724749665150, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
