# Generated by Django 4.2.15 on 2024-08-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_resume_id_alter_uploadedfile_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="responsibilities",
            field=models.TextField(blank=True, null=True),
        ),
    ]
