# Generated by Django 4.2.15 on 2024-08-27 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_resume_json"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="educations",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="experiences",
        ),
        migrations.AddField(
            model_name="education",
            name="resume",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educations",
                to="api.resume",
            ),
        ),
        migrations.AddField(
            model_name="experience",
            name="resume",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="api.resume",
            ),
        ),
    ]
