# Generated by Django 4.2.15 on 2024-10-11 12:47

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_uploadedfile_is_job_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobdescription",
            old_name="location",
            new_name="address",
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="city",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="company",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="country",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="file",
            field=models.FileField(default="", upload_to=api.models.upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="postal_code",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="state",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
