# Generated by Django 4.2.15 on 2024-10-21 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_rename_location_jobdescription_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobdescription",
            name="id",
            field=models.SlugField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
