# Generated by Django 4.2.15 on 2024-10-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_jobdescription_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="more_contact_details",
            field=models.TextField(blank=True, null=True),
        ),
    ]
