# Generated by Django 4.2.15 on 2024-10-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_resume_more_contact_details"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobdescription",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="more_contact_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
