# Generated by Django 4.2.15 on 2024-10-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_jobdescription_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobdescription",
            old_name="experienceInMonths",
            new_name="max_experience_in_months",
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="is_applicable_for_freshers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="min_experience_in_months",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="other_benefits",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobdescription",
            name="total_paid_leaves",
            field=models.IntegerField(default=0),
        ),
    ]
