# Generated by Django 4.2.15 on 2024-12-12 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_jobdescription_total_paid_leaves_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compatibility",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "resume_compatibility",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "job_compatibility",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_job",
                        to="api.jobdescription",
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compatibility_resume",
                        to="api.resume",
                    ),
                ),
            ],
        ),
    ]
