# Generated by Django 4.2.15 on 2024-12-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_compatibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="compatibility",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="compatibility",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_queue", "In Queue"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("error", "Error"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
