# Generated by Django 4.2.15 on 2024-12-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_compatibility_error_compatibility_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compatibility",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_queue", "In Queue"),
                    ("in_progress", "In Progress"),
                    ("completed", "Completed"),
                    ("is_error", "Error"),
                ],
                default="in_queue",
                max_length=20,
            ),
        ),
    ]
