# Generated by Django 4.2.15 on 2024-12-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_alter_compatibility_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compatibility",
            old_name="job",
            new_name="job_description",
        ),
    ]
