# Generated by Django 4.2.15 on 2025-01-22 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='expired_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
