# Generated by Django 4.2.15 on 2025-01-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_passwordreset_expired_at_alter_passwordreset_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='expired_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
