# Generated by Django 4.2.15 on 2025-01-23 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0036_alter_passwordreset_expired_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='JobSeeker', max_length=50)),
                ('api_key_type', models.CharField(choices=[('OpenAI_API_KEY', 'OpenAI_API_KEY'), ('GEMINI_API_KEY', 'GEMINI_API_KEY')], default='GEMINI_API_KEY', max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Recruiter', max_length=50)),
                ('api_key_type', models.CharField(choices=[('OpenAI_API_KEY', 'OpenAI_API_KEY'), ('GEMINI_API_KEY', 'GEMINI_API_KEY')], default='GEMINI_API_KEY', max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('company_description', models.TextField(max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='employer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Employer',
        ),
    ]
