# Generated by Django 4.2.15 on 2025-01-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_compatibility_user_jobdescription_user_resume_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='model',
            field=models.CharField(default='gemini', max_length=50),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='model',
            field=models.CharField(default='gemini', max_length=50),
        ),
    ]
