# Generated by Django 4.2.15 on 2025-01-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_jobseeker_model_recruiter_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='resource_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='resource_timeout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
